
version: 2

sources:
  - name: jaffle_shop
    database: dbt-tutorial
    tables:
      - name: customers
        columns:
          - name: id
          - name: first_name
          - name: last_name

      - name: orders
        columns:
          - name: id
          - name: user_id
          - name: order_date
          - name: status
          - name: _etl_loaded_at
